ios/Classes/FlutterBluePlusPlugin.m

fixed manufacturer data parsing

---

ios/Classes/FlutterBluePlusPlugin.m

Fixed an error when calling the connect method of a connected device

Fixed an error when calling the connect method of a connected device

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java

Fixed an issue where scan wasn't able to find any BLE long range devices.

Scan BLE long range -devices

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
lib/src/bluetooth_device.dart

It refresh ble services & characteristics

Add clear gatt cache method on Android

---

android/src/main/AndroidManifest.xml

Some os must use these permissions, like xiaomi (Mi OS)

Remove max sdk version

---

lib/src/utils.dart

add comments about new RxDart util classes

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java

this way multiple different types of ScanFilters can be used

allow for simultaneous MAC and ServiceUuid ScanFilters

---

README.md
android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
ios/Classes/FlutterBluePlusPlugin.m
ios/gen/Flutterblueplus.pbobjc.h
ios/gen/Flutterblueplus.pbobjc.m
lib/gen/flutterblueplus.pb.dart
lib/gen/flutterblueplus.pbenum.dart
lib/gen/flutterblueplus.pbjson.dart
lib/gen/flutterblueplus.pbserver.dart
lib/src/bluetooth_device.dart
protos/flutterblueplus.proto

cleaned up the PR from https://github.com/boskokg/flutter_blue_plus/pull/141
closes https://github.com/boskokg/flutter_blue_plus/issues/127

android: add requestConnectionPriority

---

macos/Classes/FlutterBluePlusPlugin.h
macos/Classes/FlutterBluePlusPlugin.m

In preparation for https://github.com/boskokg/flutter_blue_plus/pull/253

[MacOS] copy iOS code to macOS, in preparation for macOS support

---

lib/src/utils.dart

make sure first emitted value is actually first.

[Behavior Subject] small timing fix for first emitted value

---

README.md
android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
ios/Classes/FlutterBluePlusPlugin.m
lib/src/bluetooth_device.dart

closes: https://github.com/boskokg/flutter_blue_plus/pull/224

android: implement removeBond function

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java

[android] removeBond error handling

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java

[android] typo in removeBond

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
lib/src/bluetooth_device.dart

fixes: https://github.com/boskokg/flutter_blue_plus/issues/214

android: clearGattCache on connect to fix exception

---

ios/Classes/FlutterBluePlusPlugin.m
lib/src/bluetooth_characteristic.dart
lib/src/utils.dart

fixes: https://github.com/boskokg/flutter_blue_plus/issues/242

writeCharacteristic: exception could be missed

---

lib/src/bluetooth_characteristic.dart
lib/src/bluetooth_descriptor.dart
lib/src/utils.dart

similar to https://github.com/boskokg/flutter_blue_plus/issues/242, but for descriptors

fix missed exceptions for descriptors

---

README.md

Hopefully this is not pissing off anyone =) 
I think this is a generally good recommendation for new projects.

readme: recommend flutter_reactive_blue for new projects

---

README.md
lib/src/bluetooth_characteristic.dart
lib/src/bluetooth_descriptor.dart
lib/src/utils.dart

Fid the first issue from here: https://github.com/boskokg/flutter_blue_plus/issues/264

[Dart] add characteristic read & write mutex to avoid race conditions

---

README.md
android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
ios/Classes/FlutterBluePlusPlugin.m
ios/gen/Flutterblueplus.pbobjc.h
ios/gen/Flutterblueplus.pbobjc.m
lib/gen/flutterblueplus.pb.dart
lib/gen/flutterblueplus.pbenum.dart
lib/gen/flutterblueplus.pbjson.dart
lib/gen/flutterblueplus.pbserver.dart
lib/src/bluetooth_device.dart
macos/Classes/FlutterBluePlusPlugin.m
protos/flutterblueplus.proto

Referring to https://developer.android.com/reference/android/bluetooth/BluetoothGatt#setPreferredPhy(int,%20int,%20int)
Also I had to add a { at https://github.com/boskokg/flutter_blue_plus/compare/master...tuna-f1sh:set-preferred-phy?expand=1#diff-e49ebc6c8561aa50689fd6b03f2927d12578c1defbc53f18a26010bde8506afeR824 for current to compile on Android

[Android] support set preferred phy

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java

Last one from me hopefully! This is was also on my fork and fixes: https://github.com/boskokg/flutter_blue_plus/issues/154
Referring to https://developer.android.com/reference/android/bluetooth/BluetoothGatt#writeDescriptor(android.bluetooth.BluetoothGattDescriptor)

[Android] use new writeChar/Desc for SDK 33

---

lib/src/utils.dart

I moved this code from RxDart into our own utility function, but introduced a bug.
Broadcast-streams were being downgraded to single-streams.

[RxDart] fix doOnDone and doOnCancel not returning a broadcast stream

---

lib/src/bluetooth_characteristic.dart
lib/src/bluetooth_descriptor.dart
lib/src/utils.dart

Similar to other commits, check for success in setNotifyValue:
```
// wait for response, so that we can check for success
protos.SetNotificationResponse response = await futureResponse;
if (!response.success) {
throw Exception('setNotifyValue failed');
}
```

[BluetoothCharacteristic] check for setNotifyValue success & code cleanup

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java

Replaces deprecated enable with an Enable-Intent

---

ios/Classes/FlutterBluePlusPlugin.m
lib/src/bluetooth_characteristic.dart
lib/src/bluetooth_descriptor.dart
lib/src/bluetooth_device.dart
lib/src/bluetooth_service.dart
lib/src/flutter_blue_plus.dart
lib/src/guid.dart
lib/src/utils.dart

similar to other pull requests

[Device] fix possible missed response for connect(), disconnect() readRssi()

---

ios/Classes/FlutterBluePlusPlugin.m
lib/src/flutter_blue_plus.dart
macos/Classes/FlutterBluePlusPlugin.m

[iOS] log errors on failure, also only log success if logLevel is debug

---

lib/src/flutter_blue_plus.dart
lib/src/utils.dart

working on this issue: https://github.com/boskokg/flutter_blue_plus/issues/294

[Scan] fix issue where timeout does not close scan stream

---

ios/Classes/FlutterBluePlusPlugin.m
macos/Classes/FlutterBluePlusPlugin.m

make it easier to understand logs

[iOS] prepend all ios logs with '[FBP-iOS]' prefix

---

README.md

Update README. Add Android ProGuard rules

---

android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java

Bug Fixed:
- allowDuplicates not actually used on Android

Bug Fixed - allowDuplicates not actually used on Android

---

android/build.gradle
example/android/app/build.gradle
example/android/app/src/debug/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/profile/AndroidManifest.xml
example/android/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/pubspec.lock

This PR updates the app and plugin to Gradle 8. This will allow packages that depend on this package to also upgrade to Gradle 8.

imp: update to gradle 8

---

lib/src/flutter_blue_plus.dart

Add description to PhySupport-class

---

lib/src/flutter_blue_plus.dart

Fix cannot retrieve platform name from bondedDevices

---

README.md

Added the Official FB/FBP Discord Server in Readme. To better grow the community.

Added the Official FB/FBP Discord Server

---

README.md

Simple changes but will be helpful for newbies

README: Fix build errors in code examples

---

example/lib/screens/scan_screen.dart
example/lib/utils/utils.dart
lib/src/utils.dart

along the lines of https://github.com/boskokg/flutter_blue_plus/commit/19c3a52d2291551e96604de0cebbc0019ab39622
ref https://github.com/boskokg/flutter_blue_plus/issues/740

Remove sync:true param from example utils's Stream Controller

---

android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
lib/src/bluetooth_msgs.dart
lib/src/flutter_blue_plus.dart

[Feature] Adding Appearance support (part of advertisement data)

---

lib/src/flutter_blue_plus.dart

Fix connectedDevices type cast exception.

Fix type 'DeviceIdentifier' is not a subtype of type 'String'

---

android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
example/lib/widgets/scan_result_tile.dart
lib/src/bluetooth_msgs.dart
lib/src/flutter_blue_plus.dart

Fixes https://github.com/boskokg/flutter_blue_plus/issues/766 and https://github.com/boskokg/flutter_blue_plus/issues/202

[Feature] support advertising appearance on Android

---

android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
ios/Classes/FlutterBluePlusPlugin.m
lib/src/flutter_blue_plus.dart

Add the option to disable CBCentralManagerOptionShowPowerAlert on iOS
Disclaimer:
- I'm not an iOS developer, so please check if what I wrote makes sense
- I'm not a native English speaker, so please check if what I wrote makes sense
;-)

Issue #822

---

lib/src/flutter_blue_plus.dart

Annotate that setLogLevel is async

---

MOCKING.md

Fixes typo in MOCKING.md document

[ FIX ] Update MOCKING.md

---

android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java

Fixing https://github.com/boskokg/flutter_blue_plus/issues/785
1. Needed to change input parameters for proposed `getManufacturerSpecificData`
2. Also changed from `List<Integer>` to `byte[]`, because `getBytes` returns that, and in the other end `bytesToHex` requires that as well. So it's unnecessary weight lifting to to convert to List<Integer>. We just merge `byte[]` chunks with `System.arraycopy`.

Merging multiple MSDs with the same manufacturer ID

---

android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
lib/src/bluetooth_msgs.dart
lib/src/flutter_blue_plus.dart

Android: support legacy only scan option

---

android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java

android: stay disconnected

---

packages/flutter_blue_plus_platform_interface/lib/src/bluetooth_msgs.dart

The raw key/elements are string here and need to be converted to Guid.

Fix: conversion code for devices with service data and uuids.

---

packages/flutter_blue_plus/lib/src/flutter_blue_plus.dart
packages/flutter_blue_plus_android/lib/flutter_blue_plus_android.dart
packages/flutter_blue_plus_platform_interface/lib/flutter_blue_plus_platform_interface.dart
packages/flutter_blue_plus_platform_interface/lib/src/bluetooth_msgs.dart

[Refactor] Add on turn on response stream

---

packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart
packages/flutter_blue_plus_linux/pubspec.yaml

[Refactor] Implement on turn on response stream

---

packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart

[Refactor] Return unknown state if adaptors list empty

---

packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart

https://github.com/chipweinberger/flutter_blue_plus/pull/1191#discussion_r2060121464

[Refactor] Return stop scan false if adaptors list empty

---

packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart

https://github.com/chipweinberger/flutter_blue_plus/pull/1191#discussion_r2060121464

[Refactor] Return turn off false if adaptors list empty

---

packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart

https://github.com/chipweinberger/flutter_blue_plus/pull/1191#discussion_r2060121464

[Refactor] Return turn on false if adaptors list empty

---

packages/flutter_blue_plus/example/lib/main.dart
packages/flutter_blue_plus/example/lib/screens/device_screen.dart
packages/flutter_blue_plus/example/lib/screens/scan_screen.dart
packages/flutter_blue_plus/example/lib/utils/data_entry.dart
packages/flutter_blue_plus/example/lib/widgets/characteristic_tile.dart
packages/flutter_blue_plus/example/lib/widgets/descriptor_tile.dart
packages/flutter_blue_plus/example/lib/widgets/scan_result_tile.dart
packages/flutter_blue_plus/example/lib/widgets/service_tile.dart
packages/flutter_blue_plus/example/pubspec.lock

Added data entry UI to the example app to help testing read/write issues.
Also made some tweaks to the UI (e.g. FAP button is getting in a way with "connect" button).

data entry interface to write descs and chars and some UI tweaks in the example app
