chipweinberger/flutter_blue_plus

- ios/Classes/FlutterBluePlusPlugin.m
This change is undoing commit c7bbdf0c8dbf808c5081a8db8ed00c4eb0bce4ef / Ios : try reconnect on unexpected disconnection (fixed by EB-Plum)
That change introduces a behaviour, where the plugin code tries to connect immediately with a BLE device after it detects a disconnect from that device (except for the case where the disconnect was issued by the app). For cases where a disconnect issued by a BLE device is part of the intended work-flow, an automatic reconnect may not be desired. Furthermore, when powering-off a connected BLE device, it will go to the "connecting" state rather than being "disconnected" as expected.
It should be up to the app to decide, if it reconnects or not after a disconnect callback is received. This could be easy to achieve by setting a flag when the app …
> Remove connect to BLE device after BLE device has disconnected

- README.md
- android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
- example/lib/main.dart
- example/pubspec.lock
- ios/Classes/FlutterBluePlusPlugin.m
- ios/gen/Flutterblueplus.pbobjc.h
- ios/gen/Flutterblueplus.pbobjc.m
- lib/gen/flutterblueplus.pb.dart
- lib/gen/flutterblueplus.pbjson.dart
- lib/src/bluetooth_device.dart
- protos/flutterblueplus.proto
- protos/regenerate.md
This change adds functionality to read RSSI from a connected device. All required logic to iOS and Android native code is implemented and protos have been updated and regenerated for the required data structures
The example app was also updated to periodically show the RSSI of a connected device.
Furthermore, the regenerate.md file from flutter_blue was copied and flutter_blue_plus related changes were done to help anyone when doing future changes to protos.
> Read RSSI from a connected BLE device

- android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
The previous approach wasn't disconnecting properly and the device could be still connected under the hood as the `cancel()` was not called.
> Android - Check for the disconnected state right after the disconnect

- android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
- ios/Classes/FlutterBluePlusPlugin.m
- lib/src/flutter_blue_plus.dart
Thanks for continuing the development of flutter_blue, it's a really nice package!
This commit implements a new `FlutterBlue.name` property that will
get the friendly bluetooth name of the local bluetooth adapter.
This is the PRhttps://github.com/pauldemarco/flutter_blue/pull/1085 for this project
I tested this with my android application and it seems to be working just fine, I am not sure if the code needs to be smater if permissions for bluetooth are missing though, happy to look further into this.
Please note that I did not test this under ios, Unfortunately I have no device to test it.
The code is inferred from reading the ios docs, but I'm happy to just leave it unimplemented or add a comment if it's hard to test.
> Add `FlutterBlue.name` to get the human readable device name

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
- lib/gen/flutterblueplus.pb.dart
- lib/gen/flutterblueplus.pbjson.dart
- lib/src/flutter_blue_plus.dart
- protos/flutterblueplus.proto
Added scan with mac addresses support, has of android 8 if the screen is turned off you can only scan with filters, and these filters cannot be empty in some distributions, as I didn't have access to the UUIDs of my Bluetooth devices I decided to create this pull request with support for such a thing.
Links to information related to the pull request.
https://us.community.samsung.com/t5/Galaxy-S21/Issue-with-Bluetooth-on-S21-Ultra/td-p/1706765
https://stackoverflow.com/questions/65199141/delphi-android-scanning-bluetooth-le-devices-does-not-work-while-screen-is-off
https://stackoverflow.com/questions/48077690/ble-scan-is-not-working-when-screen-is-off-on-android-8-1-0
https://medium.com/@martijn.van.welie/making-android-ble-work-part-1-a736dcd53b02
> Scan Filter by Mac Address

- analysis_options.yaml
- example/lib/main.dart
- example/pubspec.lock
- lib/src/flutter_blue_plus.dart
- lib/src/guid.dart
- pubspec.yaml
Upgrading to linter 2.0.1, excluding generated ProtoBuf files from linting.
> Fixes #98 (or at least improves)

- android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
Here are a couple of annotations added to suppress the deprecation warnings for startLeScan/stopLeScan methods used on pre-Lollipop devices (#46).
> Prevent deprecation warnings

- lib/src/bluetooth_device.dart
This pull request removes check for an android platform when calling pair.
I am developing [flutter_blue_plus_tizen](https://github.com/JRazek/plugins/tree/flutter_blue_plus/packages/flutter_blue), plugin that uses dart implementation of flutter_blue_plus.
Pairing is in development on Tizen platform, but dart side prohibits calling the method channel.
After this change, it will throw the exception to the user when a plugin is unimplemented on a native side.
> Allow native implementation to handle pairing request

- CHANGELOG.md
- android/src/main/AndroidManifest.xml
- pubspec.yaml
This PR opts out of the `neverForLocation` permission flag on Android.
In general having to opt-in is better than having to explicitly opt-out.
Fixes: #135 Fixes: #120
> Opt out of neverForLocation on Android

- android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java
- ios/Classes/FlutterBluePlusPlugin.h
- ios/Classes/FlutterBluePlusPlugin.m
- lib/src/bluetooth_characteristic.dart
- lib/src/flutter_blue_plus.dart
Fixed an issue where iOS apps got stuck in the unknown Bluetooth state #66.
The cause of this problem was that after creating an CBCentralManager object, for a short while the state is unknown which is checked and reported by the plugin. Then two things happen in parallel:
- the plugin starts listening to the state stream,
- iOS calls centralManagerDidUpdateState with the real BT state.
If the centralManagerDidUpdateState call is faster, plugin doesn't get the first state update and is stuck in the unknown state.
Modified the code so that centralManagerDidUpdateState calls are cached before a stream event sink is attached.
I didn't see this problem on Android, but in theory it was also possible that state updates were skipped, so I modified the Android part to match changes for iOS.
> Fixes iOS apps getting stuck in unknown BT state

- lib/flutter_blue_plus.dart
- lib/src/bluetooth_characteristic.dart
- lib/src/guid.dart
- lib/src/utils.dart
- pubspec.yaml
Related Issue: https://github.com/boskokg/flutter_blue_plus/issues/236
Remove:
- convert
- collection
- meta
With this simple change, flutter_blue_plus will only have 3 dependencies:
- flutter
- rxdart
- protobuf
There are big advantages to having few dependencies. Namely, you avoid:
- a new version of a dependency causing bugs
- incompatibility between versions
- explosion of child dependencies
- unnecessary library complexity 
I understand these dependencies are some of the safest to include, but they are are incredibly simple to remove.
> [Dependencies] Remove unnecessary dependencies: convert, collection, meta

- lib/flutter_blue_plus.dart
- lib/src/bluetooth_characteristic.dart
- lib/src/bluetooth_descriptor.dart
- lib/src/bluetooth_device.dart
- lib/src/flutter_blue_plus.dart
- lib/src/utils.dart
- pubspec.yaml
Related Issue: https://github.com/boskokg/flutter_blue_plus/issues/236
**Note: this needs more testing! Draft PR.**
I've started work on removing RxDart. Please just view this commit: https://github.com/boskokg/flutter_blue_plus/pull/240/commits/3cb0a5ec36d7afcb80c017135efe6e9c0483c67f
**Motivation**: RxDart is rather complicated, often updated, and rather overkill. It is only used in a few places for what seem like trivial reasons but it's implementation is hard to understand using multiple layers of abstraction.
There are big advantages to having few dependencies. Namely, you avoid:
- a new version of a dependency causing bugs
- incompatibility between versions
- explosion of child dependencies
- unnecessary library complexity
- binary size
> [Dependencies] Remove rxdart dependency

- ios/Classes/FlutterBluePlusPlugin.m
format obj-c code with clang-format. 
Hopefully I'm not burning any bridges with this PR -- I have no strong opinions. But I found the original code too dense.
`{ColumnLimit: 120, IndentWidth: 4, BreakBeforeBraces: Allman}`
**Before:**
**After:**
> readability: use clang-format on obj-c code 

- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/lib/main.dart
- example/pubspec.yaml
see: https://github.com/boskokg/flutter_blue_plus/issues/225
> [Example] fix issue 225, android permissions

- lib/src/flutter_blue_plus.dart
Fixes: https://github.com/boskokg/flutter_blue_plus/issues/177
The bluetooth scanner Dart API does not expose the current state of the isScanning stream.
We only have access to a Stream<bool>, even though the underlying StreamController is a BehaviorSubject.
> dart api: add isScanningNow variable

- lib/src/flutter_blue_plus.dart
a "list modified while iterating" exception can occur if the user has scanning enabled, and then iterates the list with "async for"
> [Scan] always return a new list. avoids exception if user async iterates list

- lib/src/flutter_blue_plus.dart
The current method of calling stopScan on timeout causes a rogue Future if `stopScan()` if called whilst scanning, that causes erroneous stops.
For example:
1. call `startScan(timeout: 20)`
2. call after 10 seconds `stopScan()`.
3. call `startScan(timeout: 20)`
4. scan will stop due to first timeout Future after 10 seconds not 20.
5. call `startScan()`.
6. scan will stop after 10 seconds due to second call timeout even though no timeout desired.
This adds a Timer property to the class such that `stopScan()` can cancel it and prevent this behaviour.
> scan timeout timer property so can be cancelled

- README.md
- android/src/main/AndroidManifest.xml
- example/android/app/src/main/AndroidManifest.xml
- example/pubspec.lock
This will fix the Android 13 Error
```
FlutterBluePlus requires android.permission.ACCESS_FINE_LOCATION permission
```
ACCESS_FINE_LOCATION was restricted to maxSDK 30 in Plugin. This is not overwritten by App Manifest, therefore it will crash on Android 13. So i have removed that restriction.
Example and ReadME have been updated.
> #370 fix Android 13 access fine location error

- README.md
- android/src/main/AndroidManifest.xml
- example/android/app/src/main/AndroidManifest.xml
- example/lib/main.dart
- lib/src/flutter_blue_plus.dart
After inspection i've found that we do not need the ACCESS_FINE_LOCATION permission on Android 12+. But we are requesting it by default in the startScan and scan method. I've set the default to false as this flag only concerns Android 12+ (lower is always requesting fine location) and updated the example, the comments and the readME.
> handle ACCESS FINE LOCATION on Android 12+

- README.md
This PR adds a simple entry in the `README.md` file to let all new and existing users of this library know about the Proguard rule they need to add to their `proguard-rules.pro` file in order to avoid seeing obfuscation issues in their release builds.
> Include Proguard rule in README.md

- ios/Classes/FlutterBluePlusPlugin.m
When I read the device descriptor, it returns an NSString object, which only returns [0,0,0,0] in dart. So I modified it here, if it is NSString, convert it to NSData and return it.
> [iOS]fix CBDescriptor.vaule type conversion errors

- ios/Classes/FlutterBluePlusPlugin.m
Manufacturer data may only include the company ID (16 bits). We still want to parse it in this case.
See also:
https://github.com/pauldemarco/flutter_blue/pull/293/commits/bd6071fcd78ecdff61a6f64d3546aafb090cc0bf
> [iOS] fix: manufacturer data not parsed if only company ID is present

- ios/Classes/FlutterBluePlusPlugin.m
There was a crashed forced by an unknown selector: [_NSInlineData intValue]: unrecognized selector sent to instance 
I fixed this by adding a check for the class type. 
A merge would be appreciated. 
This is related to: https://github.com/pauldemarco/flutter_blue/issues/1092
Best,
Toni
> Hot fix for crash on iOS while discovering services

- android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
"getAdapterName" needs already bluetooth-permissions, at least under Android; if not any other function ("connect", "turnon" etc.) which requests permission is called before, call of "getAdapterName" ends in an exception.
Therefore "ensurePermissions"-code added before calling mBluetoothAdapter.getName().
> Android: "getAdapterName" requires bluetooth-permissions

- lib/src/bluetooth_characteristic.dart
Issue appear when I tried to crate descriptors for my characteristics with same uuid but under different services with different uuid. As result I had descriptor for all characteristics but only from first one, even if characteristic has another descriptor with another uuid or doesn't have any descriptors. With next code everything works as expected.
> Added matching of serviceUuid during characteristic search

- android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
```
E/AndroidRuntime(30132): java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
E/AndroidRuntime(30132): at com.lib.flutter_blue_plus.FlutterBluePlusPlugin$3.onScanResult(FlutterBluePlusPlugin.java:1882)
E/AndroidRuntime(30132): at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:646)
E/AndroidRuntime(30132): at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(30132): at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(30132): at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(30132): at android.app.ActivityThread.main(ActivityThread.java:8673)
E/AndroidRuntime(30132): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30132): at …
```
> [Android] Type casting error when start scan

- README.md
New changes avoid confusing beginners when setting up a plugin for only iOS mobile app.
> Doc: Fix macOS permissions section

- android/build.gradle
I found this Linter issue using Fastlane and building using Gradle: https://docs.fastlane.tools/actions/gradle/
The following command `./gradlew build -p . -s` failed
```
> Task :flutter_blue_plus:lintDebug FAILED
Lint found 41 errors, 3 warnings. First failure:
/root/.pub-cache/hosted/pub.dev/flutter_blue_plus-1.31.12/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:205: Error: Missing permissions required by BluetoothLeScanner.stopScan: android.permission.BLUETOOTH_SCAN [MissingPermission]
scanner.stopScan(getScanCallback());
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Skip linters on gradle build

- lib/src/flutter_blue_plus.dart
Fixes #876 
Test case:
```dart
print('XXX: #1 scan start: isScanningNow:${FlutterBluePlus.isScanningNow}'); // false
await FlutterBluePlus.startScan(timeout: const Duration(seconds: 15)); // SUCCESS
print('XXX: #1 scan done: isScanningNow:${FlutterBluePlus.isScanningNow}'); // true
await Future.delayed(const Duration(seconds: 2));
print('XXX: #2 scan start: isScanningNow:${FlutterBluePlus.isScanningNow}'); // true
await FlutterBluePlus.startScan(timeout: const Duration(seconds: 15)); // SUCCESS
print('XXX: #2 scan done: isScanningNow:${FlutterBluePlus.isScanningNow}'); // false
await Future.delayed(const Duration(seconds: 2));
print('XXX: #3 scan start: isScanningNow:${FlutterBluePlus.isScanningNow}'); // false
await FlutterBluePlus.startScan(timeout: const Duration(seconds: 15)); // …
```
> Fix isScanning flag when scan has already started and should be stopped before start new scan

- README.md
This pull request fixes a typo in the README file under the example for printing disconnect reasons. The previous code example incorrectly referenced `device.disconnectReasonCode` and `device.disconnectReasonDescription`. The correct properties are accessed via `device.disconnectReason?.code` and `device.disconnectReason?.description`.
Changes
Updated the README file to correct the code example:
> PR: Corrected typo in README example for disconnect reason

- lib/src/bluetooth_device.dart
- lib/src/flutter_blue_plus.dart
Addresses issue #927.
This workaround enforces a 2 second delay between connect and disconnect.
Android bug report: https://issuetracker.google.com/issues/37121040
> Android: enforce 2 second disconnect delay

- android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
Protect connect and disconnect method calls and gatt callback from concurrency by wrapping the code in critical section.
> android: add critical section to prevent concurrency

- android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
returns the correct status in `onCharacteristicChanged` as discussed in #1007, as well as adds some more GATT error strings, pulled from here: https://android.googlesource.com/platform/external/bluetooth/bluedroid/+/android-5.1.0_r1/stack/include/gatt_api.h#57
> fix: Add more GATT errors, return correct status on notify

- ios/Classes/FlutterBluePlusPlugin.m
Our app was crashing when a nearby device advertised with only 1 byte of data. This was due to the assumption that the first two bytes always contained the manufacturer ID. This fix prevents going to a negative index causing the app to crash completely.
> [Fix] iOS: crash caused by 1-byte advertisements

- packages/flutter_blue_plus/example/pubspec.lock
- packages/flutter_blue_plus/example/pubspec.yaml
- packages/flutter_blue_plus/pubspec.yaml
This PR changes how FBP dependencies are pulled in into the example app.
Also removes `publish_to: none` from `packages/flutter_blue_plus/pubspec.yaml`
@chipweinberger on a side note. It might be that converting example app to SPM on the Apple platforms was somewhat premature on my side, because most consumers still have SPM disabled. Perhaps example app changes for SPM should be reverted.
> use dependency_overrides in the example app

- packages/flutter_blue_plus/lib/src/bluetooth_device.dart
- packages/flutter_blue_plus_android/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
- packages/flutter_blue_plus_android/lib/flutter_blue_plus_android.dart
- packages/flutter_blue_plus_platform_interface/lib/src/bluetooth_msgs.dart
Hi again,
I use flutter_blue_plus to communicate with GATT peripherals that have individual PINs. I can query the PINs from a Cloud database and show them in my app, but it would be great to enter the pairing PIN automatically if the platform allows it, which is the case on Android, not on iOS (not sure about bluez, but it probably is, even though createBond is Android-only for now).
> [Android] add option to provide pairing PIN to createBond

- packages/flutter_blue_plus/lib/src/flutter_blue_plus.dart
- packages/flutter_blue_plus_platform_interface/lib/src/bluetooth_msgs.dart
- packages/flutter_blue_plus_web/lib/flutter_blue_plus_web.dart
Hey, 
In this PR I added support for [optional services](https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice#optionalservices). 
It's a required option to use device if you set no filters or you just filter by name.
More details you can find [here](https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice#acceptalldevices) and [here](https://webbluetoothcg.github.io/web-bluetooth/#dom-requestdeviceoptions-optionalservices)
> [Web] Add support for optional services

- packages/flutter_blue_plus_platform_interface/lib/src/bluetooth_msgs.dart
Currently fails with
I/flutter ( 3579): type '_Map<dynamic, dynamic>' is not a subtype of type 'Iterable<MapEntry<int, List<int>>>'
Surprisingly, the exception is swallowed somewhere without producing logs. I found this with some trial and error.
I tried some iterations of a fix and this is the most elegant way of making it work. Tested with example app on Android. Without the fix, devices don't show up, as they don't make it to dart. Surprisingly, the exception is swallowed somewhere without producing logs.
> fix: Correct casting of raw json in BmScanAdvertisement

- packages/flutter_blue_plus/README.md
This is especially important for people like me who copies the text they see blindly from such textboxes.
> [Documentation] Add clarity to positioning of ios permission request

- packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart
On some linux platforms, a disabled adapter is represented as missing.
Currently throws `Unhandled Exception: Bad state: No element`
> Fix exception when adapters is empty.

- packages/flutter_blue_plus_darwin/darwin/flutter_blue_plus_darwin/Sources/flutter_blue_plus_darwin/FlutterBluePlusPlugin.m
Seems to accidentally have been set to another method `setPreferredPhy`
> Fix errorCode for createBond on iOS

- packages/flutter_blue_plus/example/android/app/build.gradle
- packages/flutter_blue_plus/example/android/settings.gradle
- packages/flutter_blue_plus_android/android/build.gradle
This should fix Java 8 obsolete build warning below. The Flutter's core plugins been on Java 11 target for a while.
Verified using `flutter build appbundle` with the example app.
```
Running Gradle task 'bundleRelease'...                          
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
```
> fix build deprecation warnings on Android

- packages/flutter_blue_plus/lib/src/flutter_blue_plus.dart
- packages/flutter_blue_plus_android/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
- packages/flutter_blue_plus_platform_interface/lib/src/bluetooth_msgs.dart
This should address #1192 issue.
@chipweinberger @tnc1997 what are the steps to release these changes?
Need to bump version in the platform interface. With a new attribute added should it be `4.0.1 -> 4.0.2` or we need a higher version?
Similarly for Android plugin. Is `4.0.2 -> 4.0.3` ok for a new property? And the Android plugin probably shouldn't depend on `^4.0.0` version of platform as it needs newly added properties...
> [Android] location services check

- packages/flutter_blue_plus_darwin/darwin/flutter_blue_plus_darwin/Sources/flutter_blue_plus_darwin/FlutterBluePlusPlugin.m
On iOS, reading an encrypted characteristic to trigger the PIN prompt, then entering an incorrect PIN causes a crash.
```
[FBP-iOS] didUpdateValueForCharacteristic:
[FBP-iOS]   chr: 318848ff-f881-44a8-9f65-25be4801594f
[FBP-iOS]   error: Encryption is insufficient.
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]'
```
Resolved by providing a null object for `value` in the result dictionary as is done for `primary_service_uuid`.
> [iOS] Fix crash on incorrect PIN

- packages/flutter_blue_plus_android/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java
This PR fixes #1211 and it corrects the logic that detects the **Services Changed** characteristic (`0x2A05`) in `flutter_blue_plus_android`.
* The code was checking for service `0x1800` (GAP), but `0x2A05` belongs to the **GATT service** `0x1801`.
* It used `==` instead of `.equals()` for string comparison.
* It also didn't normalize the case when comparing `0x2A05`.
As a result, `onServicesReset` was never triggered, even when a valid notification was received.
* https://www.bluetooth.com/wp-content/uploads/Files/Specification/Assigned_Numbers.html
* Tested manually by modifying the plugin and using a BLE device that triggers `0x2A05`.
* Also confirmed via Dart subscription to the same characteristic, which did work.
> [Android] Fix Services Change listener - onServicesReset was not firing due to incorrect service and characteristic checks

- packages/flutter_blue_plus/lib/src/bluetooth_device.dart
- packages/flutter_blue_plus/lib/src/flutter_blue_plus.dart
- packages/flutter_blue_plus_android/lib/flutter_blue_plus_android.dart
- packages/flutter_blue_plus_darwin/lib/flutter_blue_plus_darwin.dart
- packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart
- packages/flutter_blue_plus_platform_interface/lib/flutter_blue_plus_platform_interface.dart
I propose this changes in order to collect all logs from platform, moving logging functionality from  `FlutterBluePlus` to `FlutterBluePlusPlatform`.
In this way, listeners of `FlutterBluePlus.logs` stream really catch all logs yield by all platform packages (not only from package `FlutterBluePlus`).
I test only `android` platform.
> move logging from FlutterBluePlus class to FlutterBluePlusPlatform

- packages/flutter_blue_plus/lib/src/bluetooth_device.dart
This bug has been observed on Android, but I think the fix applies to all platforms.
The following piece of code doesn't work:
```dart
BluetoothDevice btDevice = ...
// First connection
await btDevice.connect();
if (btDevice.servicesList.isEmpty) { // True
await btDevice.discoverServices(); // Called, OK
}
print("${btDevice.servicesList}"); // Has services, OK
// Something happened, we need to disconnect
await btDevice.disconnect();
// After a while, reconnect to the device
await btDevice.connect();
if (btDevice.servicesList.isEmpty) { // False, still has services from before
await btDevice.discoverServices(); // Not called 
}
final char = btDevice.servicesList.first.characteristics.first;
await char.read(); // Will throw "primary service not found"
```
The above happens because there's …
> Wipe known services on device disconnection

- packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart
On Android, setNotifyValue works by calling writeDescriptor on the gatt object, and the platform independent code waits for that notification before returning. The same is not true on Linux, where setNotify does not involve a onDescriptorWritten notification, so all of the calls to setNotifyValue (including the one in connect to listen to service changes) are hanging.
This PR simply changes setNotifyValue on Linux to return false, but it could be reworked to push a notification to that channel instead.
> [Fix] Linux: setNotifyValue: return false (no CCCD) to prevent hang

- packages/flutter_blue_plus_linux/lib/flutter_blue_plus_linux.dart
On Linux, we need to wait for BlueZ to indicate that services are ready before returning them, otherwise a partial list is usually returned.
> [Fix] Linux: discoverServices: wait for servicesResolved to avoid partial results
